BugTracker/Models/Project.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace BugTracker.Models
{
    public class Project
    {
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        [StringLength(200, ErrorMessage = "Description must be between 200 characters")]
        public string Description { get; set; }

        public Project()
        {
            this.Tickets = new HashSet<Ticket>();
            this.ProjectUsers = new HashSet<ProjectUser>();
        }

        public virtual ICollection<Ticket> Tickets { get; set; }
        public virtual ICollection<ProjectUser> ProjectUsers { get; set; }
    }
}

BugTracker/Controllers/AdminUserViewController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BugTracker.Helpers;
using BugTracker.Models;
using Microsoft.AspNet.Identity;

namespace BugTracker.Controllers
{
    public class AdminUserViewController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: AdminUserView
        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            var userRoles = new List<AdminUserViewModel>();
            foreach (ApplicationUser user in db.Users)
            {
                var myUser = new AdminUserViewModel();
                UserRolesHelper helper = new UserRolesHelper();
                myUser.UserId = user.Id;
                myUser.UserName = user.FirstName + " " + user.LastName;
                myUser.FirstName = user.FirstName;
                myUser.LastName = user.LastName;
                myUser.UserEmail = user.Email;
                myUser.CurrentRoles = helper.ListUserRoles(user.Id);
                userRoles.Add(myUser);
            }
            var sortedUsers = userRoles.OrderBy(x => x.LastName).ThenBy(p => p.FirstName).ToList();
            return View(sortedUsers);
        }
        //get method
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(string id)
        {
            var user = db.Users.Find(id);
            AdminUserViewModel AdminModel = new AdminUserViewModel();
            UserRolesHelper helper = new UserRolesHelper();

            //AdminModel.Roles = new MultiSelectList(db.Roles, "Name", "Name", selected);
            var allRoles = new List<string>();

            allRoles.Add("Submitter");
            allRoles.Add("Developer");
            allRoles.Add("Project Manager");
            allRoles.Add("Admin");

            AdminModel.RolesToSelect = new RoleCheckBox[4];
            //build an array that has all user roles and whether the user is in that role
            //this will be sent to the view
            int i = 0;
            foreach (var role in allRoles)
            {
                var checkBox = new RoleCheckBox();
                checkBox.RoleName = role;
                if (helper.IsUserInRole(id, role))
                {
                    checkBox.Checked = true;
                }
                else
                {
                    checkBox.Checked = false;
                }
                AdminModel.RolesToSelect[i] = checkBox;
                i++;
            }
            AdminModel.UserId = user.Id;
            AdminModel.UserName = user.FirstName + " " + user.LastName;
            AdminModel.UserEmail = user.Email;

            return View(AdminModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "UserId,RolesToSelect")] AdminUserViewModel admModel)
        {
            var user = db.Users.Find(admModel.UserId);
            var id = admModel.UserId;
            var allRoles = new List<string>();
            UserRolesHelper helper = new UserRolesHelper();

            allRoles.Add("Submitter");
            allRoles.Add("Developer");
            allRoles.Add("Project Manager");
            allRoles.Add("Admin");

            //build a list of selected roles based on the array in the model that was returned
            var selectedRoles = new List<string>();
            for (int i = 0; i < admModel.RolesToSelect.Length; i++)
            {
                if (admModel.RolesToSelect[i].Checked == true)
                {
                    selectedRoles.Add(admModel.RolesToSelect[i].RoleName);
                }
            }

            //if no roles have been selected, remove user from all roles
            if (selectedRoles == null)
            {
                foreach (var rRole in allRoles)
                {
                    if (helper.IsUserInRole(admModel.UserId, rRole))
                    {
                        helper.RemoveUserFromRole(admModel.UserId, rRole);
                    }
                }
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var sRole in selectedRoles)
                {
                    if (!helper.IsUserInRole(admModel.UserId, sRole))
                    {
                        helper.AddUserToRole(admModel.UserId, sRole);
                    }
                }

                var rolesToRemove = allRoles.Except(selectedRoles);
                foreach (var rRole in rolesToRemove)
                {
                    if (helper.IsUserInRole(admModel.UserId, rRole))
                    {
                        helper.RemoveUserFromRole(admModel.UserId, rRole);
                    }
                }
                return RedirectToAction("Index");
            }
        }
    }
}

BugTracker/Controllers/ProjectUserViewController.cs
using BugTracker.Helpers;
using BugTracker.Models;
using BugTracker.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace BugTracker.Controllers
{
    public class ProjectUserViewController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: ProjectUserView
        [Authorize(Roles = "Admin, Project Manager")]
        public ActionResult Edit(int? projectId)
        {
            if (projectId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var projectModel = new ProjectUserViewModel();
            Project project = db.Projects.Find(projectId);
            var helper = new ProjectUserHelper();
            // make sure project exists
            if (project != null)
            {
                projectModel.ProjectId = project.Id;
                projectModel.ProjectName = project.Name;
                //get the user Ids that are associated with the project
                var userIdList = helper.UsersInProject((int)projectId);
                var userInfoList = helper.getUserInfo(userIdList);
                projectModel.UsersAssignedtoProject = new MultiSelectList(userInfoList, "UserId", "UserName");

                //get the user Ids not associated with the project
                var nonUserIdList = helper.UsersNotInProject((int)projectId);
                var nonUserInfoList = helper.getUserInfo(nonUserIdList);
                projectModel.UsersNotAssignedToProject = new MultiSelectList(nonUserInfoList, "UserId", "UserName");
                return View(projectModel);
            }
            else
            {
                return HttpNotFound();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddUsers(int pId, string[] usersToAdd)
        {
            var helper = new ProjectUserHelper();

            if (usersToAdd == null)
            {
                //var usersToRemove = helper.UsersInProject(pId);
                //foreach (var user in usersToRemove)
                //{
                //    helper.RemoveUserFromProject(user, pId);
                //}
                return RedirectToAction("Edit", new { projectId = pId });
            }
            else
            {
                for (var i = 0; i < usersToAdd.Length; i++)
                {
                    if (!helper.IsUserInProject(usersToAdd[i], pId))
                    {
                        helper.AddUserToProject(usersToAdd[i], pId);
                    }
                }
                return RedirectToAction("Edit", new { projectId = pId });
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RemoveUsers(int pId, string[] usersToRemove)
        {
            var helper = new ProjectUserHelper();

            if (usersToRemove == null)
            {
                //var usersToRemove = helper.UsersInProject(pId);
                //foreach (var user in usersToRemove)
                //{
                //    helper.RemoveUserFromProject(user, pId);
                //}
                return RedirectToAction("Edit", new { projectId = pId });
            }
            else
            {
                for (var i = 0; i < usersToRemove.Length; i++)
                {
                    if (helper.IsUserInProject(usersToRemove[i], pId))
                    {
                        helper.RemoveUserFromProject(usersToRemove[i], pId);
                    }
                }
                return RedirectToAction("Edit", new { projectId = pId });
            }
        }


    }
}

BugTracker/Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BugTracker.Models;
using Microsoft.AspNet.Identity;

namespace BugTracker.Controllers
{
    public class ProjectsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Projects
        [Authorize]
        public ActionResult Index()
        {
            //intention here is to perform an join on the Projects table with the ProjectUsers lookup table
            //to retrieve all the projects a user is associated with
            var id = User.Identity.GetUserId();
            if (User.IsInRole("Admin"))
            {
                var myList = db.Projects.ToList();
                return View(quickReverse(db.Projects.ToList()));
            }
            else
            {
                var projects = db.Projects.Where(x => x.ProjectUsers.Any(y => y.UserId == id));
                return View(quickReverse(projects.ToList()));
            }
        }

        public List<Project> quickReverse(List<Project> oldList)
        {
            oldList.Reverse();
            return oldList;
        }

        // GET: Projects/Details/5
        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = db.Projects.Find(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            return View(project);
        }

        // GET: Projects/Create
        [Authorize(Roles = "Admin, Project Manager")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Projects/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Description")] Project project)
        {
            if (ModelState.IsValid)
            {
                db.Projects.Add(project);
                db.SaveChanges();

                ProjectUser projUser = new ProjectUser();
                projUser.UserId = User.Identity.GetUserId();
                projUser.ProjectId = project.Id;

                db.ProjectUsers.Add(projUser);
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(project);
        }

        // GET: Projects/Edit/5
        [Authorize(Roles = "Admin, Project Manager")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = db.Projects.Find(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            return View(project);
        }

        // POST: Projects/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Description")] Project project)
        {
            if (ModelState.IsValid)
            {
                db.Entry(project).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(project);
        }

        // GET: Projects/Delete/5
        [Authorize(Roles = "Admin, Project Manager")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = db.Projects.Find(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            return View(project);
        }

        // POST: Projects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Project project = db.Projects.Find(id);
            db.Projects.Remove(project);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BugTracker/Views/Projects/Create.cshtml
@model BugTracker.Models.Project

<link href="~/Content/form-style.css" rel="stylesheet">

@{
    ViewBag.Title = "Create";
}

<h2>Create Project</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.TextBoxFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })*@
                <input data-val="true" data-val-required="The Name field is required." class="form-control" id="Name" name="Name" type="text" value="" />
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.TextAreaFor(model => model.Description, new { htmlAttributes = new { @class = "form-control", @rows = "4" } })*@
                <textarea data-val="true" data-val-length="Description must be less than 200 characters" data-val-length-max="200" data-val-required="The Description field is required." class="form-control" rows="4" id="Description" name="Description"></textarea>
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")
}

BugTracker/Views/Projects/Delete.cshtml
@model BugTracker.Models.Project

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Project</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default btn-delete" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

BugTracker/Views/Projects/Details.cshtml
@model BugTracker.Models.Project
@using BugTracker.Helpers

@{
    ViewBag.Title = "Details";
}

<h2>Project Details</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>
</div>
    @if (User.IsInRole("Admin") || User.IsInRole("Project Manager"))
    {
        @Html.ActionLink("Edit Project Details", "Edit", "Projects", new { id = Model.Id }, new { @class = "btn btn-primary" })
        @Html.Raw(" ")
        @Html.ActionLink("Delete", "Delete", "Projects", new { id = Model.Id }, new { @class = "btn btn-primary btn-delete" })
    }
    <br />
    <br />
    @{
        var myHelper = new ProjectUserHelper();
        var userList = myHelper.UsersInProject(Model.Id);
        var userInfoList = myHelper.getUserInfo(userList);
    }
    @Html.Partial("_ShowProjectUsers", userInfoList, new ViewDataDictionary { { "projectId", Model.Id } })
    <br />
    <br />
<p>
    @Html.ActionLink("Back to Projects List", "Index")

</p>    

BugTracker/Views/Projects/Edit.cshtml
@model BugTracker.Models.Project

<link href="~/Content/form-style.css" rel="stylesheet">

@{
    ViewBag.Title = "Edit";
}

<h2>Edit Project</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })*@
                <input class="form-control" data-val="true" data-val-required="The Name field is required." id="Name" name="Name" type="text" value="@Model.Name" />
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.TextAreaFor(model => model.Description, new { htmlAttributes = new { @class = "form-control", @rows = "4" } })*@
                <textarea cols="20" data-val="true" data-val-length="Description must be less than 200 characters" data-val-length-max="200" data-val-required="The Description field is required." class="form-control" rows="4" id="Description" name="Description">@Model.Description</textarea>
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

BugTracker/Views/Projects/Index.cshtml
@model IEnumerable<BugTracker.Models.Project>

@{
    ViewBag.Title = "Index";
}

<h2>My Projects</h2>
@if (Model.Count() > 0)
{
    <p>
        @if (User.IsInRole("Admin") || User.IsInRole("Project Manager"))
        {
            @Html.ActionLink("Create New", "Create")
        }
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.Label("Actions")
            </th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.ActionLink("Details", "Details", new { id = item.Id })

                    @if (User.IsInRole("Admin") || User.IsInRole("Project Manager"))
                    {
                        @Html.Raw(" | ")
                        @Html.ActionLink("Edit", "Edit", new { id = item.Id })
                        @Html.Raw(" | ")
                        @Html.ActionLink("Assign Users", "Edit", "ProjectUserView", new { projectId = item.Id }, new { })
                    }
                    @*@Html.ActionLink("Delete", "Delete", new { id=item.Id })*@
                </td>
            </tr>
        }

    </table>

    <p>
        @if (User.IsInRole("Admin"))
        {
            @Html.ActionLink("Manage User Roles", "Index", "AdminUserView", null, null)
        }
    </p>
}
else
{
    <h3>
        No projects assigned. Contact your Project Manager.
    </h3>
}